### ISSUE TITLE
코드 보다가 궁금한게 있어서 질문드립니다.

### ISSUE THREAD

**Issue by jin0106** [sjyoung428/wanted-pre-onboarding-challenge-fe-1#4]
안녕하세요. 지난 8월 프론트엔드 챌리지를 같이 수강한 개발자 지망생입니다. 당시 멘토님께서 코드 작성을 잘 하셨다고 하셔서 구경을 하다가 궁금한게 있어서 질문을 할까 말까 하다가 이렇게 여쭤봅니다!
![image](https://user-images.githubusercontent.com/53500163/198558103-2306949e-1f5e-4996-81f8-1e43ec67aafb.png)

위의 코드에서 `Promise<{data: TodoData[]}>`는 getAll 메서드가 프라미스를 반환하는데 그 중 TodoData[] 타입을 가진 data를 반환하다라고 이해를 하였는데, 혹시 잘못 이해한것일까요??
그리고 clientApi.get 다음 <{data:TodoData[]}> 는 왜 필요한것인지 궁금합니다.

그리고 이렇게 작성하신 이유가 디스트럭처링 할당으로 res.data 이런식으로 하지 않고 조금이라도 간편하게 하기 위함이 맞을까요?

**Comment by sjyoung428** [comment]
@jin0106 맞습니다 제가 저 코드를 짤 당시에 아마도 data 타입에 any가 뜨는게 싫어서 작성했던것 같습니다.

**Comment by jin0106** [comment]
> @jin0106 맞습니다 제가 저 코드를 짤 당시에 아마도 data 타입에 any가 뜨는게 싫어서 작성했던것 같습니다.

답변해주셔서 감사합니다!
